# Generated by Django 3.2.1 on 2021-09-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='additionalFood',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='food',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='message',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='number',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
