# Generated by Django 3.2.1 on 2021-09-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210927_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
