# Generated by Django 3.2.1 on 2021-09-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
