# Generated by Django 3.2.1 on 2021-10-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_food_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='additionalFood',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='location',
            new_name='zipcode',
        ),
    ]
