# Generated by Django 3.2.1 on 2021-10-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20211030_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='food',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='county',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
